name: DamagesLogger
description: 
main: me.cassayre.florian.damageslogger.DamagesLogger
version: 0.1

commands:
  damageslogger:
    description: Damages Logger main command. Enter "/dl ?" for help.
    aliases: [dl]
    usage: /dl